# Generated by Django 3.2.9 on 2021-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_published_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable')], null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.IntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0, max_length=1, null=True),
        ),
    ]
